// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	//"agent/internal/biz"
	"agent/internal/conf"
	//"agent/internal/data"
	"agent/internal/server"
	//"agent/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(cfg *conf.Config, logger log.Logger) (*kratos.App, func(), error) {
	//dataData, cleanup, err := data.NewData(confData, logger)
	//if err != nil {
	//	return nil, nil, err
	//}
	//greeterRepo := data.NewGreeterRepo(dataData, logger)
	//greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	//greeterService := service.NewGreeterService(greeterUsecase)
	//grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(cfg)
	app := newApp(logger, httpServer)
	return app, func() {
		//cleanup()
	}, nil
}
