// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	//"agent/internal/biz"
	"agent/internal/conf"
	//"agent/internal/data"
	"agent/internal/server"
	//"agent/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// wireApp init kratos application.
func wireApp(cfg *conf.Config, apis *conf.Apis, logger log.Logger) (*kratos.App, func(), error) {
	httpServer := server.NewHTTPServer(cfg, apis)
	app := newApp(logger, httpServer)
	return app, func() {
		//cleanup()
	}, nil
}
